name: Android CI

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2
    - name: set up JDK 1.8
      uses: joschi/setup-jdk@v2
    - name: Build with Gradle
      run: gradle build
    - name: compile sorter
      run: javac Homework1.java
    - name: run sorter
      run: java Homework1
    - name: compiler tester
      run: javac SortingTest.java
    - name: run tester
      run: java SortingTest
      
